
resolver: lts-21.14

packages:
- '.'
extra-deps:
- io-capture-1.0.0
- xmonad-0.17.0
- xmonad-contrib-0.17.0

nix:
  enable: true
  packages:
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver
    - xorg.libXft
    - zlib
    - pkg-config-unwrapped

flags: {}

extra-package-dbs: []

