[user]
name = "Sandy Maguire"
email = "sandy@sandymaguire.me"

[ui]
default-command = ['log', '--reversed']
# diff.tool = ["difft", "--color=always", "--display=side-by-side", "$left", "$right"]
merge-editor = ["meld", "$left", "$base", "$right", "-o", "$output"]
log-synthetic-elided-nodes = false



[revsets]
log = "(trunk | changeset | avalanche | @ | roots)"

[revset-aliases]

'pruner(x)' = "mutable() & x"

old_log = "@ | roots | base::@ | @::cap | branches_and_sigils)"
'downstream(x,y)' = 'reachable(pruner(x::), pruner(y))'
'upstream(x,y)' = '(y::x) & y'
'base(x)' = 'latest(branches_and_sigils::x- & branches_and_sigils)'
'cap(x)' = 'roots(x:: & branchesandheads)'
'ctx(x)' = 'x---::x+++'
'stem(x)' = 'base(x)+ & ::x'

'sandy-root' = 'latest(pruner(description("∅")))'
'roots' = 'sandy-root'
'root' = 'sandy-root'
'branches' = 'downstream(trunk, bookmarks() | sandy-root) & mine()'
'branches_and_sigils' = 'pruner(branches | (downstream(roots, sigils)))'
'branchesandheads' = '(branches_and_sigils)'
'base' = 'base(@)'
'cap' = 'cap(@)'
'ctx' = 'ctx(@)'
'stem' = 'stem(@)'
'trunk' = 'trunk()'
'nextc' = 'roots(@:: & conflict())'

'changeset' = 'downstream(trunk, stem::cap)'
'avalanche' = 'branchesandheads'

'sigil_feat' = 'mine() & description(glob:"feat: *")'
'sigil_fix' = 'mine() & description(glob:"fix: *")'
'sigil_refactor' = 'mine() & description(glob:"refactor: *")'
'sigil_perf' = 'mine() & description(glob:"perf: *")'
'sigil_design' = 'mine() & description(glob:"design: *")'
'sigil_doc' = 'mine() & description(glob:"doc: *")'
'sigil_chore' = 'mine() & description(glob:"chore: *")'
'sigil_test' = 'mine() & description(glob:"test: *")'
'sigil_wip' = 'mine() & description(glob:"wip: *")'
'sigil_plan' = 'mine() & description(glob:"plan: *")'
'sigil_todo' = 'mine() & description(glob:"todo: *")'
'sigil_idea' = 'mine() & description(glob:"idea: *")'
'sigil_ci' = 'mine() & description(glob:"ci: *")'
'sigil_checkpoint' = 'mine() & description(glob:"checkpoint: *")'
'sigil_tool' = 'mine() & description(glob:"tool: *")'
'sigil_folded' = 'mine() & description(glob:"... *")'

'sigils' = 'pruner(sigil_feat | sigil_perf | sigil_refactor | sigil_design | sigil_doc | sigil_chore | sigil_test | sigil_wip | sigil_plan | sigil_fix | sigil_todo | sigil_idea | sigil_ci | sigil_tool | sigil_folded | sigil_checkpoint)'


'tree' = "(trunk::) & mine()"

[template-aliases]
# 'format_short_id(id)' = 'id.shortest()'
'format_timestamp(timestamp)'="timestamp.ago()"

[signing]
sign-all = true
backend = "ssh"
key = "~/.ssh/id_rsa.pub"

[fix.tools.maniga-format]
command = ["fourmolu", "--mode", "stdout", "--check-idempotence", "--stdin-input-file", "$path"]

patterns = ["glob:'**/*.hs'"]
# command = ["/home/sandy/prj/manifold/maniga/tools/format.sh", "-f $path"]

[git]
subprocess=true
auto_import = false
auto_export = false

[[--scope]]
--when.commands = ["log"]

[--scope.ui]
paginate = "never"

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
